### ISSUE TITLE
getEntityDetailsVaultAggregated provides no way to set aggregation_level to "Global"

### ISSUE THREAD

**Issue by kevinforrestconnors** [radixdlt/babylon-gateway#591]

**Comment by dhedey** [comment]
Hi @kevinforrestconnors - I'm not quite sure I follow what you mean. By definition if you have vault aggregation, you are concerned about the individual balance of each vault, not of globally aggregated balances. The two are in some sense incompatible.

I might have misunderstood though - please come to our Discord server as per the [Community Involvement](https://github.com/radixdlt/babylon-gateway/blob/main/README.md#community-involvement) section of our readme, and we'll be happy to discuss further.

Just to note - we're going to close Issues on this repository, as we currently use Discord instead for discussions, reports and requests. We may re-open them in future.
