### ISSUE TITLE
Paging through the NonFungibleIds of a resource does not work properly

### ISSUE THREAD

**Issue by backyard-coder** [radixdlt/babylon-gateway#96]
When paging through all the NonFungibleIds of a resource and accumulating all IDs in a list, that list will in the end contain some duplicate IDs but there will also be some IDs missing from the list. I tried with a collection of 10 NFTs and used a page limit of 2. I only got 8 unique IDs out. Two requests returned one duplicate ID each:

```
Loaded page using cursor: null: [65537, 0]
Loaded page using cursor: {"o":2}: [262148, 131074]
Loaded page using cursor: {"o":4}: [262148, 327685]
Loaded page using cursor: {"o":6}: [458759, 524296]
Loaded page using cursor: {"o":8}: [524296, 589833]
```   

I suspect the problem may be found here:
https://github.com/radixdlt/babylon-gateway/blob/4f34959dfb43a5200847cf7bae8a323bbefdec92/src/RadixDlt.NetworkGateway.PostgresIntegration/Services/EntityStateQuerier.cs#L285-L343

The problem can be reproduced using this request. Please execute five times, each time updating the `cursor` field:
```bash
curl --location --request POST 'https://betanet.radixdlt.com/non-fungible/ids' \
--header 'Content-Type: application/json' \
--data-raw '{
    "address": "resource_tdx_b_1qzrdqdl3c7pfkl507fljl49w3ejjmngx80ghgj6trmmsknff89",
    "limit": 2,
    "cursor": "null"
}'
``

**Comment by dhedey** [comment]
Thanks for the report @backyard-coder ! This should have been fixed with the release of Betanet-V2 today.
